from auth import get_password_hash



def _generated_foods() -> list[dict]:
    generated = []

    grain_names = [
        "Jowar Roti",
        "Whole Wheat Roti",
        "Barley Khichda",
        "Red Rice",
        "Millet Pulao",
        "Poha",
        "Dalia Upma",
        "Cornmeal Porridge",
        "Amaranth Khichdi",
        "Foxtail Millet Bowl",
        "Little Millet Upma",
        "Kodo Millet Rice",
    ]
    lentil_names = [
        "Urad Dal",
        "Chana Dal",
        "Rajma Curry",
        "Chole Curry",
        "Green Moong Curry",
        "Horsegram Soup",
        "Black Chana Curry",
        "Moth Bean Curry",
        "Sprouted Moong Salad",
        "Lobia Curry",
        "Matki Usal",
        "Mixed Dal",
    ]
    vegetable_names = [
        "Lauki Sabzi",
        "Tori Sabzi",
        "Bhindi Stir Fry",
        "Cabbage Peas",
        "Carrot Beans Stir Fry",
        "Pumpkin Curry",
        "Ash Gourd Curry",
        "Ridge Gourd Curry",
        "Cauliflower Stir Fry",
        "Broccoli Saute",
        "Drumstick Curry",
        "Beetroot Poriyal",
        "Fenugreek Leaves Sabzi",
        "Spinach Stir Fry",
        "Bottle Gourd Soup",
    ]
    fruit_names = [
        "Guava",
        "Pear",
        "Muskmelon",
        "Watermelon",
        "Orange",
        "Mosambi",
        "Sapota",
        "Kiwi",
        "Black Grapes",
        "Pineapple",
    ]
    beverage_names = [
        "Cumin Water",
        "Ajwain Water",
        "Fennel Water",
        "Tulsi Tea",
        "Mint Tea",
        "Lemon Honey Water",
        "Jeera Buttermilk",
        "Coriander Water",
        "Warm Lime Water",
        "Cinnamon Tea",
    ]
    nuts_seed_names = [
        "Pumpkin Seeds",
        "Sunflower Seeds",
        "Chia Seeds",
        "Walnuts",
        "Cashews",
        "Pistachios",
        "Sesame Seeds",
        "Peanuts Roasted",
    ]
    prepared_names = [
        "Vegetable Upma",
        "Rava Idli",
        "Vegetable Poha",
        "Lemon Rice",
        "Curd Rice",
        "Khichdi with Vegetables",
        "Vegetable Pulao",
        "Tomato Rice",
        "Moong Chilla",
        "Besan Chilla",
        "Vegetable Soup Bowl",
        "Paneer Salad Bowl",
    ]

    for i, name in enumerate(grain_names, start=1):
        generated.append(
            {
                "name": name,
                "name_hindi": None,
                "category": "Grains",
                "subcategory": "Whole Grain",
                "calories": 105 + (i % 6) * 12,
                "protein_g": 2.5 + (i % 4) * 1.1,
                "carbs_g": 18 + (i % 7) * 3.0,
                "fat_g": 0.8 + (i % 3) * 0.6,
                "fiber_g": 1.2 + (i % 4) * 1.0,
                "rasa": "Sweet",
                "virya": "Neutral" if i % 2 else "Warming",
                "vipaka": "Sweet",
                "vata_effect": -1 if i % 3 else 0,
                "pitta_effect": 0,
                "kapha_effect": -1 if i % 2 else 0,
                "is_pathya_for": ["weight_loss"] if i % 2 else ["fatigue"],
                "is_apathya_for": [],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Generated grain option for balanced meal plans.",
            }
        )

    for i, name in enumerate(lentil_names, start=1):
        generated.append(
            {
                "name": name,
                "name_hindi": None,
                "category": "Lentils/Pulses",
                "subcategory": "Protein",
                "calories": 110 + (i % 5) * 14,
                "protein_g": 7.2 + (i % 5) * 1.4,
                "carbs_g": 16 + (i % 5) * 2.7,
                "fat_g": 0.6 + (i % 4) * 0.4,
                "fiber_g": 4.5 + (i % 5) * 1.2,
                "rasa": "Astringent",
                "virya": "Warming",
                "vipaka": "Pungent",
                "vata_effect": 1 if i % 3 == 0 else 0,
                "pitta_effect": 0,
                "kapha_effect": -1,
                "is_pathya_for": ["weight_loss", "muscle_gain"],
                "is_apathya_for": ["gas"] if i % 3 == 0 else [],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Generated pulse option with high protein.",
            }
        )

    for i, name in enumerate(vegetable_names, start=1):
        generated.append(
            {
                "name": name,
                "name_hindi": None,
                "category": "Vegetables",
                "subcategory": "Cooked",
                "calories": 28 + (i % 5) * 10,
                "protein_g": 1.0 + (i % 4) * 0.8,
                "carbs_g": 4 + (i % 6) * 2.1,
                "fat_g": 0.2 + (i % 3) * 0.5,
                "fiber_g": 1.5 + (i % 5) * 1.0,
                "rasa": "Bitter" if i % 2 else "Sweet",
                "virya": "Cooling",
                "vipaka": "Sweet",
                "vata_effect": 1 if i % 4 == 0 else 0,
                "pitta_effect": -1,
                "kapha_effect": -1 if i % 3 else 0,
                "is_pathya_for": ["acidity", "constipation"],
                "is_apathya_for": ["vata_imbalance", "thyroid"] if i % 4 == 0 else [],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Generated vegetable option for dosha-friendly meals.",
            }
        )

    for i, name in enumerate(fruit_names, start=1):
        generated.append(
            {
                "name": name,
                "name_hindi": None,
                "category": "Fruits",
                "subcategory": "Fresh",
                "calories": 42 + (i % 6) * 9,
                "protein_g": 0.3 + (i % 3) * 0.4,
                "carbs_g": 9 + (i % 6) * 2.4,
                "fat_g": 0.2 + (i % 2) * 0.2,
                "fiber_g": 1.3 + (i % 5) * 0.8,
                "rasa": "Sweet",
                "virya": "Cooling",
                "vipaka": "Sweet",
                "vata_effect": 0,
                "pitta_effect": -1,
                "kapha_effect": 1 if i % 4 == 0 else -1,
                "is_pathya_for": ["digestion"],
                "is_apathya_for": ["obesity", "diabetes"] if i % 4 == 0 else ["diabetes"] if i % 3 == 0 else [],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Generated fruit option for snacks.",
            }
        )

    for i, name in enumerate(beverage_names, start=1):
        generated.append(
            {
                "name": name,
                "name_hindi": None,
                "category": "Beverages",
                "subcategory": "Herbal",
                "calories": 8 + (i % 5) * 7,
                "protein_g": 0.1 + (i % 3) * 0.2,
                "carbs_g": 1 + (i % 5) * 1.5,
                "fat_g": 0.0,
                "fiber_g": 0.1,
                "rasa": "Pungent" if i % 2 else "Sweet",
                "virya": "Warming" if i % 2 else "Cooling",
                "vipaka": "Pungent",
                "vata_effect": -1 if i % 2 else 0,
                "pitta_effect": 1 if i % 3 == 0 else -1,
                "kapha_effect": -1,
                "is_pathya_for": ["indigestion"],
                "is_apathya_for": ["acidity"] if i % 3 == 0 else [],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Generated beverage option for rituals/snacks.",
            }
        )

    for i, name in enumerate(nuts_seed_names, start=1):
        generated.append(
            {
                "name": name,
                "name_hindi": None,
                "category": "Nuts & Seeds",
                "subcategory": "Snack",
                "calories": 460 + (i % 6) * 28,
                "protein_g": 11 + (i % 5) * 2.0,
                "carbs_g": 10 + (i % 4) * 3.3,
                "fat_g": 30 + (i % 5) * 4.5,
                "fiber_g": 5 + (i % 5) * 2.1,
                "rasa": "Sweet",
                "virya": "Warming",
                "vipaka": "Sweet",
                "vata_effect": -1,
                "pitta_effect": 1 if i % 3 == 0 else 0,
                "kapha_effect": 1 if i % 2 else -1,
                "is_pathya_for": ["fatigue"],
                "is_apathya_for": ["obesity"] if i % 2 else [],
                "is_vegetarian": True,
                "season_best": "Winter",
                "description": "Generated nuts/seeds option, portion control needed.",
            }
        )

    for i, name in enumerate(prepared_names, start=1):
        generated.append(
            {
                "name": name,
                "name_hindi": None,
                "category": "Prepared Dishes",
                "subcategory": "Meal",
                "calories": 90 + (i % 7) * 24,
                "protein_g": 3 + (i % 5) * 1.9,
                "carbs_g": 12 + (i % 7) * 4.2,
                "fat_g": 1.0 + (i % 5) * 1.3,
                "fiber_g": 1.5 + (i % 4) * 1.4,
                "rasa": "Sweet",
                "virya": "Neutral",
                "vipaka": "Sweet",
                "vata_effect": -1 if i % 2 else 0,
                "pitta_effect": -1 if i % 3 else 0,
                "kapha_effect": 1 if i % 4 == 0 else -1,
                "is_pathya_for": ["digestion"],
                "is_apathya_for": ["obesity", "hypertension"] if i % 4 == 0 else ["heart_disease"] if i % 3 == 0 else [],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Generated prepared dish for practical meal slots.",
            }
        )

    return generated


async def seed_defaults() -> None:
    from datetime import datetime, timezone

    from models import DietTemplate, Food, User

    if await User.find_one(User.email == "admin@ayurdiet.com") is None:
        await User(
            name="Super Admin",
            email="admin@ayurdiet.com",
            password_hash=get_password_hash("admin1234"),
            role="admin",
            created_at=datetime.now(timezone.utc),
        ).insert()

    if await User.find_one(User.email == "doctor@ayurdiet.com") is None:
        await User(
            name="Demo Doctor",
            email="doctor@ayurdiet.com",
            password_hash=get_password_hash("demo1234"),
            role="doctor",
            created_at=datetime.now(timezone.utc),
        ).insert()

    templates_data = [
        ("Vata-Pacifying", "Vata", "Balancing", "Warm, grounding, nourishing foods.", {
            "Breakfast": {"time": "07:30-08:30", "categories": ["Grains", "Dairy", "Prepared Dishes"]},
            "Lunch": {"time": "12:00-13:00", "categories": ["Prepared Dishes", "Vegetables", "Lentils/Pulses", "Grains"]},
            "Evening Snack": {"time": "16:00-17:00", "categories": ["Nuts & Seeds", "Fruits", "Beverages"]},
            "Dinner": {"time": "19:00-20:00", "categories": ["Vegetables", "Lentils/Pulses", "Prepared Dishes"]},
        }),
        ("Pitta-Pacifying", "Pitta", "Balancing", "Cooling, mildly sweet and bitter foods.", {
            "Breakfast": {"time": "07:30-08:30", "categories": ["Fruits", "Grains", "Dairy"]},
            "Lunch": {"time": "12:00-13:00", "categories": ["Vegetables", "Grains", "Lentils/Pulses", "Prepared Dishes"]},
            "Evening Snack": {"time": "16:00-17:00", "categories": ["Fruits", "Beverages"]},
            "Dinner": {"time": "19:00-20:00", "categories": ["Vegetables", "Grains", "Prepared Dishes"]},
        }),
        ("Kapha-Pacifying", "Kapha", "Balancing", "Light, warming, and stimulating foods.", {
            "Breakfast": {"time": "07:30-08:30", "categories": ["Grains", "Beverages"]},
            "Lunch": {"time": "12:00-13:00", "categories": ["Lentils/Pulses", "Vegetables", "Grains"]},
            "Evening Snack": {"time": "16:00-17:00", "categories": ["Fruits", "Nuts & Seeds"]},
            "Dinner": {"time": "19:00-20:00", "categories": ["Vegetables", "Lentils/Pulses"]},
        }),
        ("Pitta Weight Loss", "Pitta", "Weight Loss", "Moderate calories with pitta-safe meals.", {
            "Breakfast": {"time": "07:30-08:30", "categories": ["Fruits", "Grains"]},
            "Lunch": {"time": "12:00-13:00", "categories": ["Vegetables", "Lentils/Pulses"]},
            "Evening Snack": {"time": "16:00-17:00", "categories": ["Beverages", "Fruits"]},
            "Dinner": {"time": "19:00-20:00", "categories": ["Vegetables", "Lentils/Pulses"]},
        }),
        ("Kapha Weight Loss", "Kapha", "Weight Loss", "Light meals to reduce heaviness.", {
            "Breakfast": {"time": "07:30-08:30", "categories": ["Beverages", "Fruits"]},
            "Lunch": {"time": "12:00-13:00", "categories": ["Vegetables", "Lentils/Pulses"]},
            "Evening Snack": {"time": "16:00-17:00", "categories": ["Beverages"]},
            "Dinner": {"time": "19:00-20:00", "categories": ["Vegetables"]},
        }),
        ("Tridosha Balancing", "Tridosha", "General Wellness", "Balanced plan for all doshas.", {
            "Breakfast": {"time": "07:30-08:30", "categories": ["Grains", "Fruits", "Dairy"]},
            "Lunch": {"time": "12:00-13:00", "categories": ["Prepared Dishes", "Vegetables", "Lentils/Pulses", "Grains"]},
            "Evening Snack": {"time": "16:00-17:00", "categories": ["Fruits", "Nuts & Seeds", "Beverages"]},
            "Dinner": {"time": "19:00-20:00", "categories": ["Vegetables", "Lentils/Pulses", "Prepared Dishes", "Grains"]},
        }),
    ]
    
    for name, vikriti, goal, desc, slots in templates_data:
        await DietTemplate.get_motor_collection().update_one(
            {"name": name},
            {"$set": {
                "name": name,
                "target_vikriti": vikriti,
                "goal": goal,
                "description": desc,
                "meal_slots": slots
            }},
            upsert=True
        )

    foods = [
            {
                "name": "Moong Dal Khichdi",
                "name_hindi": "मूंग दाल खिचड़ी",
                "category": "Prepared Dishes",
                "subcategory": "Lunch",
                "calories": 140,
                "protein_g": 5.0,
                "carbs_g": 24.0,
                "fat_g": 2.5,
                "fiber_g": 3.0,
                "rasa": "Sweet",
                "virya": "Cooling",
                "vipaka": "Sweet",
                "vata_effect": -1,
                "pitta_effect": -1,
                "kapha_effect": 0,
                "is_pathya_for": ["acidity", "ibs"],
                "is_apathya_for": [],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Light and digestible one-pot meal.",
            },
            {
                "name": "Bajra Roti",
                "name_hindi": "बाजरा रोटी",
                "category": "Grains",
                "subcategory": "Flatbread",
                "calories": 230,
                "protein_g": 7.0,
                "carbs_g": 42.0,
                "fat_g": 3.0,
                "fiber_g": 8.0,
                "rasa": "Sweet",
                "virya": "Warming",
                "vipaka": "Sweet",
                "vata_effect": 1,
                "pitta_effect": 0,
                "kapha_effect": -1,
                "is_pathya_for": ["diabetes"],
                "is_apathya_for": ["constipation"],
                "is_vegetarian": True,
                "season_best": "Winter",
                "description": "Millet flatbread with warming qualities.",
            },
            {
                "name": "Steamed Bottle Gourd",
                "name_hindi": "लौकी",
                "category": "Vegetables",
                "subcategory": "Cooked",
                "calories": 35,
                "protein_g": 1.0,
                "carbs_g": 7.0,
                "fat_g": 0.2,
                "fiber_g": 1.5,
                "rasa": "Sweet",
                "virya": "Cooling",
                "vipaka": "Sweet",
                "vata_effect": 0,
                "pitta_effect": -1,
                "kapha_effect": 0,
                "is_pathya_for": ["acidity", "hypertension"],
                "is_apathya_for": [],
                "is_vegetarian": True,
                "season_best": "Summer",
                "description": "Hydrating and gentle vegetable.",
            },
            {
                "name": "Soaked Almonds",
                "name_hindi": "भीगे बादाम",
                "category": "Nuts & Seeds",
                "subcategory": "Snack",
                "calories": 579,
                "protein_g": 21.0,
                "carbs_g": 22.0,
                "fat_g": 50.0,
                "fiber_g": 12.5,
                "rasa": "Sweet",
                "virya": "Warming",
                "vipaka": "Sweet",
                "vata_effect": -1,
                "pitta_effect": 0,
                "kapha_effect": 1,
                "is_pathya_for": ["fatigue"],
                "is_apathya_for": ["obesity"],
                "is_vegetarian": True,
                "season_best": "Winter",
                "description": "Nourishing snack in moderation.",
            },
            {
                "name": "Buttermilk",
                "name_hindi": "छाछ",
                "category": "Beverages",
                "subcategory": "Digestive",
                "calories": 40,
                "protein_g": 3.3,
                "carbs_g": 4.8,
                "fat_g": 0.9,
                "fiber_g": 0.0,
                "rasa": "Sour",
                "virya": "Cooling",
                "vipaka": "Sour",
                "vata_effect": 0,
                "pitta_effect": 1,
                "kapha_effect": -1,
                "is_pathya_for": ["indigestion"],
                "is_apathya_for": ["acidity"],
                "is_vegetarian": True,
                "season_best": "Summer",
                "description": "Digestive probiotic drink.",
            },
            {
                "name": "Papaya",
                "name_hindi": "पपीता",
                "category": "Fruits",
                "subcategory": "Fresh",
                "calories": 43,
                "protein_g": 0.5,
                "carbs_g": 11.0,
                "fat_g": 0.3,
                "fiber_g": 1.7,
                "rasa": "Sweet",
                "virya": "Cooling",
                "vipaka": "Sweet",
                "vata_effect": 0,
                "pitta_effect": -1,
                "kapha_effect": -1,
                "is_pathya_for": ["constipation"],
                "is_apathya_for": [],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Digestive fruit rich in enzymes.",
            },
            {
                "name": "Masoor Dal",
                "name_hindi": "मसूर दाल",
                "category": "Lentils/Pulses",
                "subcategory": "Dal",
                "calories": 116,
                "protein_g": 9.0,
                "carbs_g": 20.0,
                "fat_g": 0.4,
                "fiber_g": 8.0,
                "rasa": "Astringent",
                "virya": "Warming",
                "vipaka": "Pungent",
                "vata_effect": 1,
                "pitta_effect": 0,
                "kapha_effect": -1,
                "is_pathya_for": ["weight_loss"],
                "is_apathya_for": ["gas"],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Protein-rich red lentil preparation.",
            },
            {
                "name": "Toor Dal",
                "name_hindi": "अरहर दाल",
                "category": "Lentils/Pulses",
                "subcategory": "Dal",
                "calories": 121,
                "protein_g": 7.5,
                "carbs_g": 21.0,
                "fat_g": 1.2,
                "fiber_g": 6.0,
                "rasa": "Sweet",
                "virya": "Warming",
                "vipaka": "Sweet",
                "vata_effect": 0,
                "pitta_effect": 0,
                "kapha_effect": -1,
                "is_pathya_for": ["fatigue"],
                "is_apathya_for": [],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Comforting staple dal for lunch and dinner.",
            },
            {
                "name": "Oats Porridge",
                "name_hindi": "ओट्स दलिया",
                "category": "Prepared Dishes",
                "subcategory": "Breakfast",
                "calories": 88,
                "protein_g": 3.0,
                "carbs_g": 16.0,
                "fat_g": 1.8,
                "fiber_g": 2.0,
                "rasa": "Sweet",
                "virya": "Neutral",
                "vipaka": "Sweet",
                "vata_effect": -1,
                "pitta_effect": 0,
                "kapha_effect": 0,
                "is_pathya_for": ["cholesterol"],
                "is_apathya_for": [],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Easy-to-digest morning porridge.",
            },
            {
                "name": "Ragi Porridge",
                "name_hindi": "रागी दलिया",
                "category": "Prepared Dishes",
                "subcategory": "Breakfast",
                "calories": 95,
                "protein_g": 2.8,
                "carbs_g": 18.0,
                "fat_g": 1.1,
                "fiber_g": 2.4,
                "rasa": "Sweet",
                "virya": "Cooling",
                "vipaka": "Sweet",
                "vata_effect": 0,
                "pitta_effect": -1,
                "kapha_effect": 0,
                "is_pathya_for": ["bone_health"],
                "is_apathya_for": [],
                "is_vegetarian": True,
                "season_best": "Summer",
                "description": "Calcium-rich millet porridge.",
            },
            {
                "name": "Methi Thepla",
                "name_hindi": "मेथी थेपला",
                "category": "Prepared Dishes",
                "subcategory": "Breakfast",
                "calories": 220,
                "protein_g": 6.0,
                "carbs_g": 32.0,
                "fat_g": 7.0,
                "fiber_g": 5.0,
                "rasa": "Bitter",
                "virya": "Warming",
                "vipaka": "Pungent",
                "vata_effect": 0,
                "pitta_effect": 1,
                "kapha_effect": -1,
                "is_pathya_for": ["diabetes"],
                "is_apathya_for": ["acidity"],
                "is_vegetarian": True,
                "season_best": "Winter",
                "description": "Fenugreek flatbread for travel-friendly meals.",
            },
            {
                "name": "Jeera Rice",
                "name_hindi": "जीरा राइस",
                "category": "Grains",
                "subcategory": "Rice",
                "calories": 130,
                "protein_g": 2.4,
                "carbs_g": 28.0,
                "fat_g": 0.6,
                "fiber_g": 0.5,
                "rasa": "Sweet",
                "virya": "Neutral",
                "vipaka": "Sweet",
                "vata_effect": -1,
                "pitta_effect": 0,
                "kapha_effect": 1,
                "is_pathya_for": ["low_appetite"],
                "is_apathya_for": ["obesity"],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Simple rice with cumin for digestion.",
            },
            {
                "name": "Brown Rice",
                "name_hindi": "ब्राउन राइस",
                "category": "Grains",
                "subcategory": "Rice",
                "calories": 111,
                "protein_g": 2.6,
                "carbs_g": 23.0,
                "fat_g": 0.9,
                "fiber_g": 1.8,
                "rasa": "Sweet",
                "virya": "Neutral",
                "vipaka": "Sweet",
                "vata_effect": 0,
                "pitta_effect": 0,
                "kapha_effect": -1,
                "is_pathya_for": ["weight_loss", "diabetes"],
                "is_apathya_for": [],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Whole grain rice with higher fiber.",
            },
            {
                "name": "Quinoa Upma",
                "name_hindi": "क्विनोआ उपमा",
                "category": "Prepared Dishes",
                "subcategory": "Breakfast",
                "calories": 120,
                "protein_g": 4.2,
                "carbs_g": 20.0,
                "fat_g": 2.2,
                "fiber_g": 3.0,
                "rasa": "Astringent",
                "virya": "Neutral",
                "vipaka": "Sweet",
                "vata_effect": 1,
                "pitta_effect": 0,
                "kapha_effect": -1,
                "is_pathya_for": ["weight_loss"],
                "is_apathya_for": ["vata_imbalance"],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "High-protein upma alternative.",
            },
            {
                "name": "Paneer Bhurji",
                "name_hindi": "पनीर भुर्जी",
                "category": "Prepared Dishes",
                "subcategory": "Main",
                "calories": 265,
                "protein_g": 14.0,
                "carbs_g": 8.0,
                "fat_g": 18.0,
                "fiber_g": 1.5,
                "rasa": "Sweet",
                "virya": "Heating",
                "vipaka": "Sweet",
                "vata_effect": -1,
                "pitta_effect": 1,
                "kapha_effect": 1,
                "is_pathya_for": ["muscle_gain"],
                "is_apathya_for": ["acidity"],
                "is_vegetarian": True,
                "season_best": "Winter",
                "description": "Soft paneer scramble with spices.",
            },
            {
                "name": "Palak Soup",
                "name_hindi": "पालक सूप",
                "category": "Beverages",
                "subcategory": "Soup",
                "calories": 45,
                "protein_g": 2.6,
                "carbs_g": 6.0,
                "fat_g": 1.0,
                "fiber_g": 2.1,
                "rasa": "Bitter",
                "virya": "Cooling",
                "vipaka": "Pungent",
                "vata_effect": 1,
                "pitta_effect": -1,
                "kapha_effect": -1,
                "is_pathya_for": ["anemia"],
                "is_apathya_for": ["vata_imbalance"],
                "is_vegetarian": True,
                "season_best": "Winter",
                "description": "Iron-rich spinach soup.",
            },
            {
                "name": "Carrot Beet Salad",
                "name_hindi": "गाजर चुकंदर सलाद",
                "category": "Vegetables",
                "subcategory": "Salad",
                "calories": 58,
                "protein_g": 1.4,
                "carbs_g": 12.0,
                "fat_g": 0.4,
                "fiber_g": 3.4,
                "rasa": "Sweet",
                "virya": "Cooling",
                "vipaka": "Sweet",
                "vata_effect": 1,
                "pitta_effect": -1,
                "kapha_effect": -1,
                "is_pathya_for": ["constipation"],
                "is_apathya_for": ["vata_imbalance"],
                "is_vegetarian": True,
                "season_best": "Winter",
                "description": "Fiber-rich colorful salad.",
            },
            {
                "name": "Coconut Water",
                "name_hindi": "नारियल पानी",
                "category": "Beverages",
                "subcategory": "Hydration",
                "calories": 19,
                "protein_g": 0.7,
                "carbs_g": 3.7,
                "fat_g": 0.2,
                "fiber_g": 1.1,
                "rasa": "Sweet",
                "virya": "Cooling",
                "vipaka": "Sweet",
                "vata_effect": 0,
                "pitta_effect": -1,
                "kapha_effect": 0,
                "is_pathya_for": ["dehydration", "acidity"],
                "is_apathya_for": [],
                "is_vegetarian": True,
                "season_best": "Summer",
                "description": "Natural electrolyte drink.",
            },
            {
                "name": "Amla Juice",
                "name_hindi": "आंवला जूस",
                "category": "Beverages",
                "subcategory": "Herbal",
                "calories": 44,
                "protein_g": 0.9,
                "carbs_g": 10.0,
                "fat_g": 0.6,
                "fiber_g": 1.5,
                "rasa": "Sour",
                "virya": "Cooling",
                "vipaka": "Sweet",
                "vata_effect": 0,
                "pitta_effect": -1,
                "kapha_effect": -1,
                "is_pathya_for": ["immunity"],
                "is_apathya_for": ["cold"],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Vitamin C-rich rejuvenating juice.",
            },
            {
                "name": "Ginger Tea",
                "name_hindi": "अदरक चाय",
                "category": "Beverages",
                "subcategory": "Herbal",
                "calories": 12,
                "protein_g": 0.1,
                "carbs_g": 2.8,
                "fat_g": 0.0,
                "fiber_g": 0.1,
                "rasa": "Pungent",
                "virya": "Warming",
                "vipaka": "Sweet",
                "vata_effect": -1,
                "pitta_effect": 1,
                "kapha_effect": -1,
                "is_pathya_for": ["indigestion"],
                "is_apathya_for": ["acidity"],
                "is_vegetarian": True,
                "season_best": "Monsoon",
                "description": "Warm digestive herbal tea.",
            },
            {
                "name": "Turmeric Milk",
                "name_hindi": "हल्दी दूध",
                "category": "Beverages",
                "subcategory": "Night Drink",
                "calories": 98,
                "protein_g": 4.2,
                "carbs_g": 10.0,
                "fat_g": 4.5,
                "fiber_g": 0.3,
                "rasa": "Bitter",
                "virya": "Warming",
                "vipaka": "Pungent",
                "vata_effect": -1,
                "pitta_effect": 1,
                "kapha_effect": 0,
                "is_pathya_for": ["joint_pain", "sleep"],
                "is_apathya_for": ["acidity"],
                "is_vegetarian": True,
                "season_best": "Winter",
                "description": "Golden milk for recovery and sleep.",
            },
            {
                "name": "Roasted Chana",
                "name_hindi": "भुना चना",
                "category": "Nuts & Seeds",
                "subcategory": "Snack",
                "calories": 164,
                "protein_g": 9.0,
                "carbs_g": 27.0,
                "fat_g": 2.6,
                "fiber_g": 7.6,
                "rasa": "Astringent",
                "virya": "Warming",
                "vipaka": "Pungent",
                "vata_effect": 1,
                "pitta_effect": 0,
                "kapha_effect": -1,
                "is_pathya_for": ["weight_loss"],
                "is_apathya_for": ["gas"],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "High-fiber crunchy snack.",
            },
            {
                "name": "Flax Seeds",
                "name_hindi": "अलसी के बीज",
                "category": "Nuts & Seeds",
                "subcategory": "Seeds",
                "calories": 534,
                "protein_g": 18.0,
                "carbs_g": 29.0,
                "fat_g": 42.0,
                "fiber_g": 27.0,
                "rasa": "Nutty",
                "virya": "Warming",
                "vipaka": "Pungent",
                "vata_effect": -1,
                "pitta_effect": 1,
                "kapha_effect": -1,
                "is_pathya_for": ["cholesterol"],
                "is_apathya_for": ["acidity"],
                "is_vegetarian": True,
                "season_best": "Winter",
                "description": "Omega-3 rich seeds in small portions.",
            },
            {
                "name": "Apple",
                "name_hindi": "सेब",
                "category": "Fruits",
                "subcategory": "Fresh",
                "calories": 52,
                "protein_g": 0.3,
                "carbs_g": 14.0,
                "fat_g": 0.2,
                "fiber_g": 2.4,
                "rasa": "Sweet",
                "virya": "Cooling",
                "vipaka": "Sweet",
                "vata_effect": 0,
                "pitta_effect": -1,
                "kapha_effect": -1,
                "is_pathya_for": ["constipation"],
                "is_apathya_for": [],
                "is_vegetarian": True,
                "season_best": "Autumn",
                "description": "Light fruit for snacks.",
            },
            {
                "name": "Pomegranate",
                "name_hindi": "अनार",
                "category": "Fruits",
                "subcategory": "Fresh",
                "calories": 83,
                "protein_g": 1.7,
                "carbs_g": 19.0,
                "fat_g": 1.2,
                "fiber_g": 4.0,
                "rasa": "Sweet-Astringent",
                "virya": "Cooling",
                "vipaka": "Sweet",
                "vata_effect": -1,
                "pitta_effect": -1,
                "kapha_effect": 0,
                "is_pathya_for": ["anemia"],
                "is_apathya_for": [],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Raktavardhak fruit with antioxidant support.",
            },
            {
                "name": "Banana",
                "name_hindi": "केला",
                "category": "Fruits",
                "subcategory": "Fresh",
                "calories": 89,
                "protein_g": 1.1,
                "carbs_g": 23.0,
                "fat_g": 0.3,
                "fiber_g": 2.6,
                "rasa": "Sweet",
                "virya": "Cooling",
                "vipaka": "Sweet",
                "vata_effect": -1,
                "pitta_effect": -1,
                "kapha_effect": 1,
                "is_pathya_for": ["fatigue"],
                "is_apathya_for": ["obesity"],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Quick-energy fruit.",
            },
            {
                "name": "Chicken Soup",
                "name_hindi": "चिकन सूप",
                "category": "Non-Veg",
                "subcategory": "Soup",
                "calories": 86,
                "protein_g": 10.0,
                "carbs_g": 2.0,
                "fat_g": 4.0,
                "fiber_g": 0.0,
                "rasa": "Salty",
                "virya": "Warming",
                "vipaka": "Pungent",
                "vata_effect": -1,
                "pitta_effect": 1,
                "kapha_effect": 0,
                "is_pathya_for": ["recovery"],
                "is_apathya_for": ["acidity"],
                "is_vegetarian": False,
                "season_best": "Winter",
                "description": "Protein-rich restorative soup.",
            },
            {
                "name": "Grilled Fish",
                "name_hindi": "ग्रिल्ड मछली",
                "category": "Non-Veg",
                "subcategory": "Main",
                "calories": 128,
                "protein_g": 20.0,
                "carbs_g": 0.0,
                "fat_g": 4.5,
                "fiber_g": 0.0,
                "rasa": "Salty",
                "virya": "Warming",
                "vipaka": "Pungent",
                "vata_effect": -1,
                "pitta_effect": 1,
                "kapha_effect": -1,
                "is_pathya_for": ["muscle_gain"],
                "is_apathya_for": ["pitta_imbalance"],
                "is_vegetarian": False,
                "season_best": "All",
                "description": "Lean protein non-veg option.",
            },
            {
                "name": "Vegetable Stew",
                "name_hindi": "मिक्स वेज स्टू",
                "category": "Prepared Dishes",
                "subcategory": "Dinner",
                "calories": 92,
                "protein_g": 3.2,
                "carbs_g": 15.0,
                "fat_g": 2.1,
                "fiber_g": 3.8,
                "rasa": "Sweet",
                "virya": "Neutral",
                "vipaka": "Sweet",
                "vata_effect": -1,
                "pitta_effect": -1,
                "kapha_effect": 0,
                "is_pathya_for": ["digestion"],
                "is_apathya_for": [],
                "is_vegetarian": True,
                "season_best": "Monsoon",
                "description": "Warm one-pot dinner option.",
            },
            {
                "name": "Idli",
                "name_hindi": "इडली",
                "category": "Prepared Dishes",
                "subcategory": "Breakfast",
                "calories": 58,
                "protein_g": 2.0,
                "carbs_g": 12.0,
                "fat_g": 0.3,
                "fiber_g": 0.8,
                "rasa": "Sweet",
                "virya": "Cooling",
                "vipaka": "Sweet",
                "vata_effect": 0,
                "pitta_effect": -1,
                "kapha_effect": 0,
                "is_pathya_for": ["indigestion"],
                "is_apathya_for": [],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Steamed fermented rice cake.",
            },
            {
                "name": "Vegetable Dalia",
                "name_hindi": "वेजिटेबल दलिया",
                "category": "Prepared Dishes",
                "subcategory": "Breakfast",
                "calories": 102,
                "protein_g": 3.6,
                "carbs_g": 18.0,
                "fat_g": 2.2,
                "fiber_g": 3.4,
                "rasa": "Sweet",
                "virya": "Neutral",
                "vipaka": "Sweet",
                "vata_effect": -1,
                "pitta_effect": 0,
                "kapha_effect": -1,
                "is_pathya_for": ["weight_loss"],
                "is_apathya_for": [],
                "is_vegetarian": True,
                "season_best": "All",
                "description": "Balanced breakfast with whole grain and vegetables.",
            },
    ]
    foods.extend(_generated_foods())

    # Insert or update foods
    for food_dict in foods:
        await Food.get_motor_collection().update_one(
            {"name": food_dict["name"]},
            {"$set": food_dict},
            upsert=True
        )

